### PR TITLE
added making figure scripts

### LINKED ISSUE #1: Add code and docs
@chenminbnu to add existing code for any figures and pre-processing necessary to reproduce what is represented in the paper.

### PR DESCRIPTION
**Pull request by chenminbnu**
added code for plotting figures in the paper .

### CODE REVIEW

**Comment by chenminbnu** [comment]
added postprocessing scripts for intermediate results


Resolves #1

**Review by crvernon — CHANGES_REQUESTED** [review]
@chenminbnu just need to add the supporting functions that we discussed via phone and I'll test again.  Thanks!

**Comment by chenminbnu** [comment]
script and files are updated to reflect the supporting functions and data.

**Comment by chenminbnu** [comment]
add supporting functions and data for GMDfigures.m

**Comment by chenminbnu** [comment]
fix bugs in Figure 8

**Review by crvernon — APPROVED** [review]

**Comment by crvernon** [comment]
I tested the `GMD_makefigures.m` code to success.  The postprocessing code uses the data from the Demeter run outputs that can be reproduced using the data minted - see README.txt in this repository.

Resolves #1

**Pull request merged**
